### PR TITLE
Fix for YAML files for resources and CI/CD

### PR DESCRIPTION
**Pull request by Anirudh-S-Kumar**

### CODE REVIEW

**Comment by Anirudh-S-Kumar** [comment]
@Anindya-Prithvi I have added quotes around the square brackets, which should fix the YAML build

**Comment by aflah02** [comment]
LGTM, let's merge and see!

**Comment by Anirudh-S-Kumar** [comment]
The YAML file still needs to be changed here 
https://github.com/aflah02/SemWiseResourcesIIIT/blob/953f6c73ca0e9df5a2a86523091b8b50fcde975a/.github/workflows/main.yml#L37

This should be changed to 
```sh
git add .
```
instead

**Comment by aflah02** [comment]
Ah right
I thought you changed it 
Thanks will do!

**Pull request merged**
