### PR TITLE
Moving to YAML + CI/CD

### LINKED ISSUE #24: Tasty themed github.io page
- restructure readme to yaml
- spam <table><tr><td>
- add current README.md to CI/CD using GH actions

### PR DESCRIPTION
**Pull request by aflah02**
Fixes #24

### CODE REVIEW

**Comment by aflah02** [comment]
@Anindya-Prithvi Thoughts?

**Comment by aflah02** [comment]
The 2 notebooks are just for converting the current README to yaml and then testing the function

The YAML is fairly straightforward to alter and uses markdown syntax directly instead of adding multiple fields to not overcomplicate stuff

**Review by Anindya-Prithvi — CHANGES_REQUESTED** [review]
add 
```diff
on:
+   workflow_dispatch:
    push:
         branched:
```
to manually trigger as needed


Also python version kinda old, but should be alr for the moment

**Review by Anindya-Prithvi — COMMENTED** [review]
*.ipynb notebooks do not seem useful anymore? Since they have been already committed once, i believe they can be safely deleted from this patch

**Review by Anindya-Prithvi — APPROVED** [review]
Approved
image

**Comment by Anindya-Prithvi** [comment]
Review https://github.com/aflah02/SemWiseResourcesIIIT/pull/26

**Comment by aflah02** [comment]
GG LGTM

**Pull request merged**
