### PR TITLE
Transition to mkdocs-material

### PR DESCRIPTION
**Pull request by Anirudh-S-Kumar**
Big pull request cuz lots of changes have been done

### CODE REVIEW

**Comment by Anirudh-S-Kumar** [comment]
Do note the link for the site in mkdocs.yml needs to be changed to https://aflah02.github.io/SemWiseResourcesIIIT/

**Comment by aflah02** [comment]
At a high level this looks really good, I'll take a closer look later tonight or tomorrow!
Thanks for the work!!

**Comment by Anirudh-S-Kumar** [comment]
I have already changed the URL and some other things

**Review by Anindya-Prithvi — CHANGES_REQUESTED** [review]
looks good, but i think we you can remove the redundant files from the PR, i.e. the files which are getting "generated"?

**Comment by Anirudh-S-Kumar** [comment]
you mean the ones in the docs?

**Review by Anindya-Prithvi — APPROVED** [review]
LGTM. Later we can push the python stuff inside another folder and we could have only resources.yaml, README.md, .gitignore and .github/workflows visible at the root level. 

also add the GH pages link to the README+ Sidebar of the repo

**Comment by aflah02** [comment]
LGTM as well
Thanks!

**Pull request merged**
